### ISSUE TITLE
Figure out how to do styling now that AmbientTextStyle and AmbientContentColor are gone

### ISSUE THREAD

**Issue by zach-klippenstein** [halilozercan/compose-richtext#27]
In [alpha07](https://developer.android.com/jetpack/androidx/releases/compose-animation#1.0.0-alpha07), these were moved from foundation into material libraries.

We can no longer automatically style text, instead we need to provide hooks for converting rich text style into whatever ambients you need to for your design systems.

Another possible option is providing our own mini design system, with our own text components that directly consume the rich text themes.

**Comment by grandstaish** [comment]
Hi Zach, have you considered making a "basic" version of `RichText`? Similar to the foundational [BasicText](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/BasicText.kt;l=46?q=BasicText.kt). E.g.: 

```
@Composable
public fun BasicRichText(
  modifier: Modifier = Modifier,
  textStyle: TextStyle = TextStyle.Default,
  richTextStyle: RichTextStyle? = null,
  children: @Composable RichTextScope.() -> Unit
)
```

Then design systems could easily add their own `RichText` composable that sets the correct `TextStyle` (which includes a color). And if you want to keep the convenience of having a composable that works out-of-the-box for Material, then we could also add a `richtext-material` module that sets up the `textStyle` using `LocalTextStyle` and `LocalContentColor`. 

Note: we would also need to do this split for the Markdown composable too. 

(For context, we're hoping to use this library for its markdown support, but at the moment there's no way for us to set the default `TextStyle` since we don't use Material in our app)

**Comment by zach-klippenstein** [comment]
Basic Rich Text sounds like an oxymoron to me. I would think a better solution would be to build the necessary styling primitives into this library, since it is basically a design system itself. I haven't thought much about how to do that though, and how to make it flexible enough to use from other design systems.

Curious what Siyamed and Sean think about this.

**Comment by objcode** [comment]
Ahoy!

First, I'd love to get input on the current API design here, as well as share our thinking.

## Splitting theme aware and themed composables

We made an intentional choice in Compose to make `BasicText` theme agnostic. It's expected that real-world usage of compose will have companies (and design libraries) define their own theme system as they will need features that don't fit 1-1 with the Material system. In the simplest case, this may be adding a few extra brand colors, but some systems and designers will likely define an entire alternative typography system.

Looking at this library, it feels very foundational and provides general features that will be useful even in non-material apps, so I'd suggest taking a similar approach. Specifically, this would look like

```
@Composable fun BasicRichText(...) // theme-agnostic composable that's responsible for just displaying text
@Composable fun RichText(...) // Material-theme integration that reads the correct styles then calls BasicRichText
```

Then, a developer that's working in a `Fancy` design system can define `FancyRichText` in their app code to call `BasicRichText` with the appropriate styling.

A few notes that we found as we did this split:

1. Functionality related to displaying rich text should be defined as features on `BasicRichText`
2. Functionality related to the design system only should be defined in `RichText`

## Integrating with a theme from a design system

Avoiding design-related ambients in `BasicRichText` will make it easy to integrate with alternative design systems. Then, even if you do introduce type dependencies in the formal arguments that differ from the types used in the alternative design system (e.g. they use `FancyTextStyle`), a theme wrapper like the Material `RichText` proposed above would be the only place that does the type translation.

## Defining your own theme system

This one is a bit more of a judgement call - and is something that could make sense given the size of the library. Here's some things to consider

- (-1) Can the styling be defined accurately using only `MaterialTheme`?
- (-1) Will developers see it as a second theme system just to use this library while the rest of their app uses another theme?
- (+1) Is there a clear advantage to the styling information you can provide in `RichTextTheme` (e.g. bullet shapes etc)
- (+1) Can an adapter from Material to the custom theme be built to avoid duplicating colors etc?

In this case, I personally think this will be easier to use by integrating with `MaterialTheme`. However, if there's a clear reason to provide an alternative system (e.g. bullet shapes would be a good reason) then it might make sense to define a new theme and exposing integrations for both. Material for devs that don't need the rich formatting, and the custom system for devs that do. You can also build an adapter from MaterialTheme->RichTextTheme to avoid duplication of colors etc.

**Comment by zach-klippenstein** [comment]
Thanks for the detailed writeup Sean! I need to play with this to prove to figure out the details. Unless @halilozercan beats me to it, since he seems to have the right idea and clearly has a real use case to drive it.

**Comment by halilozercan** [comment]
I wish I could beat you to it but 3 months long curfew has just been lifted in Turkey so I'll be outside as much as I can, before the inevitable return of curfew 😄 Btw, thanks a lot for this writeup Sean! It is a great summary of theming and styling philosophy of Compose, which got me confused after the `BasicText` transition.

**Comment by halilozercan** [comment]
~~https://github.com/halilozercan/compose-richtext/pull/2~~

~~PR is not worthy of a review for now. Hence, it's targeted to my fork. I would appreciate just a skim through of the new ideas. If we land on a common ground for the new changes, I can make the PR ready for review in short time.~~

https://github.com/zach-klippenstein/compose-richtext/pull/32

PR is now targeting the correct repository

**Comment by zach-klippenstein** [comment]
I have a question about this part of @objcode's comment:

> Avoiding design-related ambients in BasicRichText will make it easy to integrate with alternative design systems. Then, even if you do introduce type dependencies in the formal arguments that differ from the types used in the alternative design system (e.g. they use FancyTextStyle), a theme wrapper like the Material RichText proposed above would be the only place that does the type translation.

If the decision is for this library to make its own theme, then why would using our own theme composition locals make Material integration trickier? The RichText -> BasicRichText wrapper would still be the only place where that conversion would have to happen, regardless of whether we used locals or something else. 

Also, not 100% sure what you mean by "formal arguments" here - as in function arguments instead of implicit locals?

**Comment by halilozercan** [comment]
#45 resolves this issue. I'm going to keep this issue open for a little while longer for potential discussion.
