### ISSUE TITLE
Failed to resolve: org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev764

### ISSUE THREAD

**Issue by dessalines** [halilozercan/compose-richtext#93]
I get this error when trying to use this library.

`implementation "com.halilibo.compose-richtext:richtext-ui-android-debug:0.14.1"`

edit: `0.13.0` worked for now.

**Comment by jari-kuipers** [comment]
Also experiencing this issue

**Comment by morrisseyai** [comment]
If you're using a reasonably current version of Compose and this problem is isolated to your Android configuration then it's likely you already have the AndroidX Compose runtime in your dependencies, so you might want to declare the library dependency like this:
```
// note I used richtext-commonmark here, but use whichever you require
implementation("com.halilibo.compose-richtext:richtext-commonmark:0.14.1") {
    exclude(group = "org.jetbrains.compose.runtime")
    exclude(group = "org.jetbrains.compose.foundation")
}
```

Can confirm this works with no runtime issues for Compose version `1.2.1` and `1.3.0-rc01`
